### ISSUE TITLE
`make l10n` doesn't create translations for all `supported_languages`

### ISSUE THREAD

**Issue by ankushhKapoor** [vacanza/holidays#2441]
Currently, running `make l10n` generates `.po` files only for the language set as `default_language`. However, it would be more efficient and contributor-friendly if `.po` files were generated for **all `supported_languages`** instead.

This would avoid the need to manually change the `default_language` and re-run the command for each language, especially when working on or reviewing translations across multiple languages.

Let me know what you think.

**Comment by Wasif-Shahzad** [comment]
I'd like to work on this

**Comment by arkid15r** [comment]
@ankushhKapoor do you plan to finish this?

**Comment by ankushhKapoor** [comment]
> @ankushhKapoor do you plan to finish this?

Hi @arkid15r , thank you for the follow-up! I’m currently out of station and don’t have access to my laptop. I plan to open a PR for this in about 8–10 days once I’m back. Appreciate your patience!

**Comment by arkid15r** [comment]
This is addressed in https://github.com/vacanza/holidays/pull/2607

**Comment by Wasif-Shahzad** [comment]
> This is addressed in [#2607](https://github.com/vacanza/holidays/pull/2607)

I believe this isn't fixed. I just created the .po files for Palestine and I had to do the old process. @arkid15r

**Comment by KJhellico** [comment]
Try `l10n_helper.py` script 😉

**Comment by ankushhKapoor** [comment]
> I believe this isn't fixed. I just created the .po files for Palestine and I had to do the old process. [@arkid15r](https://github.com/arkid15r)

Check description of #2607 

> 1. Make sure that `default_language `and `supported_languages `are specified in code.
> 2. Run `make l10n` or `python scripts/l10n/generate_po_files.py` (to create .pot file).
> 3. Run `python scripts/l10n/l10n_helper.py MM --create-po --overwrite `(MM is the country code hereinafter). This will create .po files for all supported languages. If you don't need .csv files, you can stop here and just work with .po files using your usual methods. For en_US locale, translations will be retrieved from msg comments (!).

Read this carefully.
